name: secure_call
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter_bloc: ^8.1.3
  flutter_contacts: ^1.1.7+1
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  introduction_screen: ^3.1.12
  country_picker: ^2.0.23
  lottie: ^3.0.0
  flutter:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo/logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/logo/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/logo/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/logo/logo.png"

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Black.ttf
        - asset: fonts/Montserrat/Montserrat-BlackItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
        - asset: fonts/Montserrat/Montserrat-BoldItalic.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Italic.ttf
        - asset: fonts/Montserrat/Montserrat-Light.ttf
        - asset: fonts/Montserrat/Montserrat-LightItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
        - asset: fonts/Montserrat/Montserrat-MediumItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
        - asset: fonts/Montserrat/Montserrat-ThinItalic.ttf
    - family: Source Sans 3
      fonts:
        - asset: fonts/Source_Sans_3/SourceSans3-Black.ttf
        - asset: fonts/Source_Sans_3/SourceSans3-BlackItalic.ttf
        - asset: fonts/Source_Sans_3/SourceSans3-Bold.ttf
        - asset: fonts/Source_Sans_3/SourceSans3-BoldItalic.ttf
        - asset: fonts/Source_Sans_3/SourceSans3-ExtraBold.ttf
        - asset: fonts/Source_Sans_3/SourceSans3-ExtraBoldItalic.ttf
        - asset: fonts/Source_Sans_3/SourceSans3-ExtraLight.ttf
        - asset: fonts/Source_Sans_3/SourceSans3-ExtraLightItalic.ttf
        - asset: fonts/Source_Sans_3/SourceSans3-Italic.ttf
        - asset: fonts/Source_Sans_3/SourceSans3-Light.ttf
        - asset: fonts/Source_Sans_3/SourceSans3-LightItalic.ttf
        - asset: fonts/Source_Sans_3/SourceSans3-Medium.ttf
        - asset: fonts/Source_Sans_3/SourceSans3-MediumItalic.ttf
        - asset: fonts/Source_Sans_3/SourceSans3-Regular.ttf
        - asset: fonts/Source_Sans_3/SourceSans3-SemiBold.ttf
        - asset: fonts/Source_Sans_3/SourceSans3-SemiBoldItalic.ttf